### PR TITLE
adding Duos benchmarks

### PR DESCRIPTION
**Pull request by Thomas-Ulrich**
Starting from : https://gitlab.lrz.de/ru58zid/benchmarks/

1) I ve removed all meshes (large files).
2) remove pdf in LOH.
3) harmonized TPV to tpv.
4) removed the png files
5) remove WP2_LOH3/loh.cad (empty)

### CODE REVIEW

**Comment by Thomas-Ulrich** [comment]
I added Northidge. 
Removed the mesh and the asagi file. We would need a script to get the asagi file.

**Comment by krenzland** [comment]
The meshes are indeed a problem. Putting them onto git is not really a smart idea.
The ideal solution would be hosting them on some server that we can access, e.g. on whatever server that's running seissol.org?

There's also another benchmark repo: https://gitlab.lrz.de/seissol.org/benchmarks
It contains mostly convergence tests but also some other test cases.

**Comment by sebwolf-de** [comment]
Another possibility would be to provide all the scripts to generate the meshes by yourself. IIRC all meshes in the cookbook are generated with gmsh (and pumgen afterwards), both of which are publicly available.

**Comment by krenzland** [comment]
Yes, I agree with that. Pumgen is a bit hard to install but assuming that spack support is coming soon, this wouldn't be a problem.

**Comment by uphoffc** [comment]
Why don't you put large files on zenodo?

**Comment by krenzland** [comment]
> Why don't you put large files on zenodo?

Not really familiar with that service - isn't this more effort than just dumping the files somewhere?

**Comment by Thomas-Ulrich** [comment]
Hi,
So at the end, I was able to describe the procedure to generate the mesh files of all setups with gmsh (except for tpv29, but Duo should help me documented this one also).
Zenodo seems like a good idea, but probably we do not need it, thanks to these gmsh scripts.

**Comment by AliceGabriel** [comment]
Thanks Thomas and Duo! Zenodo is a great idea (we would get a DOI and can
be cited) but having the gmsh scripts in one place with everything else is
even better.

**Comment by daisy20170101** [comment]
I feel it's better to provide both scripts and mesh files for the cookbook. Users could still run the examples even if they don't want to do the mesh by themselves. And it's better to put all these files in a separated repo. e.g. Zenodo. It is an option to download the examples.

**Comment by Thomas-Ulrich** [comment]
Hi,
So the pull request is now open for reviews.
I did not include the procedure for tpv29 mesh generation, because I m not satisfied with the mesh generated.
I push the procedure to another branch, which could be merged if the identified problems are fixed.

**Comment by daisy20170101** [comment]
All changes have been checked.

**Comment by Thomas-Ulrich** [comment]
just something that I thought.
Might be better to replace the source.srf and LOH1_source_50.dat by scripts to generate them?
(source.srf is half a mega). @daisy20170101 Do you have such script?

**Pull request merged**
