### PR TITLE
Update runner.py

### PR DESCRIPTION
**Pull request by ravil-mobile**
changed `analysis.csv` file format. 

* Requires an underscore. Used to have a hyphen

### CODE REVIEW

**Comment by ravil-mobile** [comment]
Ok. Then I will close this PR and make a change in `AnalysisWriter.h`

Is it ok?

**Comment by krenzland** [comment]
Why change AnalysisWriter?

**Comment by ravil-mobile** [comment]
> Why change AnalysisWriter?

It is going to result in a small change in `dr/cpp`.

here is the current master branch (also used to be in `dr/cpp`):
https://github.com/SeisSol/SeisSol/blob/5d85df973f0b0af4052ccdd064c4424899521e16/src/ResultWriter/AnalysisWriter.h#L60

and here is what we have in the current `dr/cpp` branch
https://github.com/SeisSol/SeisSol/blob/d358af7513b2eee7662ce4a8c7664074d858839d/src/ResultWriter/AnalysisWriter.h#L60

and here is what our runner script is searching
https://github.com/SeisSol/Examples/blob/ad72e6b2ccc828c4e8318b78708b0a057a22db0b/convergence_elastic/elastic_convergence_runner/runner.py#L99

So, it is easy for me to change  `AnalysisWriter.h` in `dr/cpp`

**Comment by krenzland** [comment]
Ah, in dr/cpp. That makes sense then.
I'll close this PR then by your suggestion.

**Pull request closed without merging**
